

export const SVG_SPRITE = {
  soundcloud: '#soundcloud',
  twitter: '#twitter',
  paypal: '#paypal',
  github: '#github',
  email: '#email',
  telegram: '#telegram',
  wechat: '#wechat',
  linkedin: '#linkedin',
  facebook: '#facebook',
  instagram: '#instagram',
  fire: '#flame',
  new: '#new',
  heart: '#heart',
  emptyHeart: '#passion',
  tag: '#price-tag',
  topRank: '#popularity',
  moon: '#moon',
  sun: '#sun',
  moon2: '#moon-2',
  sun2: '#sun-2',
  announcement: '#megaphone',
  home: '#home',
  home2: '#home-2',
  blog: '#pencil',
  music: '#music',
  music2: '#music-2',
  cv: '#resume-and-cv',
  search: '#magnifying-glass',
  clock: '#clock',
  eye: '#eye',
  like: '#like',
  folder: '#closed-container',
  archive: '#archive',
  more: '#menu'
}